package com.apxpert.weien.controller;

import com.apxpert.weien.dto.OrderDTO;
import com.apxpert.weien.dto.Result;
import com.apxpert.weien.entity.Customer;
import com.apxpert.weien.service.MemberService;
import com.apxpert.weien.service.OrderService;
import com.apxpert.weien.utils.UserHolder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("api")
public class OrderController {
    @Autowired
    private OrderService orderService;
    @Autowired
    private MemberService memberService;


    @PostMapping("orders")
    public Result createOrder(@RequestBody OrderDTO orderDTO) {
        Customer loginUser = UserHolder.getUser();
        Customer customer = orderDTO.getCustomer();
        if (loginUser == null) {
            // 未登入狀態, 自動生成一個顧客會員
            customer = memberService.autoGenerated(customer);
            UserHolder.saveUser(customer);
        }

        OrderDTO order = orderService.createOrder(orderDTO);
        if (!order.getSuccess()) {
            return Result.fail("庫存不足");
        }

        order.setCustomer(customer);
        return Result.ok(order);
    }

    @GetMapping("orders")
    public Result getOrders(@RequestParam(defaultValue = "0") Integer page, @RequestParam(defaultValue = "20") Integer size) {
        Page<OrderDTO> orderList = orderService.getOrderList(page, size);
        return Result.ok(orderList.getContent(), orderList.getTotalElements());
    }
}
