package com.apxpert.weien.service;

import com.apxpert.weien.dto.MemberDTO;
import com.apxpert.weien.entity.Customer;

public interface MemberService {
    Customer autoGenerated (Customer customer);
}
